import * as THREE from 'three';
import { OrbitControls } from 'three/examples/jsm/controls/OrbitControls.js';

const COLORS = { cyan:0x29e7ff, blue:0x4b7cff, violet:0x7c4dff, magenta:0xff4fd8, orange:0xffa438, lime:0x8dff72, yellow:0xffef65, white:0xf7fbff, dark:0x07111f };
const LABEL_CACHE = new Map();

function roundedBox(w,h,d,r=.16){ const shape=new THREE.Shape(); const x=-w/2,y=-h/2; shape.moveTo(x+r,y); shape.lineTo(x+w-r,y); shape.quadraticCurveTo(x+w,y,x+w,y+r); shape.lineTo(x+w,y+h-r); shape.quadraticCurveTo(x+w,y+h,x+w-r,y+h); shape.lineTo(x+r,y+h); shape.quadraticCurveTo(x,y+h,x,y+h-r); shape.lineTo(x,y+r); shape.quadraticCurveTo(x,y,x+r,y); return new THREE.ExtrudeGeometry(shape,{depth:d,bevelEnabled:true,bevelSegments:3,steps:1,bevelSize:.05,bevelThickness:.05}); }
function textSprite(text,color='#ffffff',size=30){ const key=`${text}:${color}:${size}`, cached=LABEL_CACHE.get(key); if(cached) return cached.clone(); const canvas=document.createElement('canvas'),ctx=canvas.getContext('2d'); ctx.font=`700 ${size}px Inter, Arial`; const width=Math.ceil(ctx.measureText(text).width+34); canvas.width=width; canvas.height=size+28; ctx.font=`700 ${size}px Inter, Arial`; ctx.textAlign='center'; ctx.textBaseline='middle'; ctx.fillStyle=color; ctx.fillText(text,width/2,canvas.height/2); const tex=new THREE.CanvasTexture(canvas); tex.colorSpace=THREE.SRGBColorSpace; const sprite=new THREE.Sprite(new THREE.SpriteMaterial({map:tex,transparent:true,depthWrite:false})); sprite.scale.set(width/90,canvas.height/90,1); LABEL_CACHE.set(key,sprite); return sprite.clone(); }
function lineBetween(a,b,color=COLORS.cyan,opacity=.45){ const geo=new THREE.BufferGeometry().setFromPoints([a,b]); return new THREE.Line(geo,new THREE.LineBasicMaterial({color,transparent:true,opacity})); }
function glowMaterial(color,emissive=1.2,opacity=1){ return new THREE.MeshStandardMaterial({color,emissive:color,emissiveIntensity:emissive,roughness:.26,metalness:.28,transparent:opacity<1,opacity}); }

export class AIWorld {
  constructor(container){
    this.container=container; this.clock=new THREE.Clock(); this.raycaster=new THREE.Raycaster(); this.pointer=new THREE.Vector2(); this.activeGroup=new THREE.Group(); this.effects=[]; this.interactive=[]; this.neuronParams={inputA:.7,inputB:.35,weightA:1.2,weightB:-.6,bias:.15}; this.tokenText='Artificial intelligence is amazing.'; this.generationSpeed=1.1; this.denoise=0; this.sound=false;
    this.scene=new THREE.Scene(); this.scene.background=new THREE.Color(0x07121f); this.scene.fog=new THREE.FogExp2(0x07121f,.035);
    this.camera=new THREE.PerspectiveCamera(46,1,.1,120); this.camera.position.set(0,1.2,10);
    this.renderer=new THREE.WebGLRenderer({antialias:true,alpha:false,powerPreference:'high-performance'}); this.renderer.outputColorSpace=THREE.SRGBColorSpace; this.renderer.toneMapping=THREE.ACESFilmicToneMapping; this.renderer.toneMappingExposure=1.15; this.renderer.shadowMap.enabled=true; this.renderer.shadowMap.type=THREE.PCFSoftShadowMap; container.appendChild(this.renderer.domElement);
    this.controls=new OrbitControls(this.camera,this.renderer.domElement); this.controls.enableDamping=true; this.controls.enablePan=false; this.controls.minDistance=4; this.controls.maxDistance=16; this.controls.target.set(0,.5,0);
    this.scene.add(this.activeGroup); this.setupLights(); this.setupBackground(); this.bind(); this.resize(); this.ready=Promise.resolve(); this.animate();
  }
  setupLights(){ const hemi=new THREE.HemisphereLight(0x9beeff,0x120e2c,1.7); this.scene.add(hemi); const key=new THREE.DirectionalLight(0xffffff,3.4); key.position.set(4,7,5); key.castShadow=true; this.scene.add(key); const cyan=new THREE.PointLight(COLORS.cyan,18,16); cyan.position.set(-4,2,3); this.scene.add(cyan); const pink=new THREE.PointLight(COLORS.magenta,14,14); pink.position.set(4,1,1); this.scene.add(pink); }
  setupBackground(){ const count=innerWidth<700?90:180,pos=new Float32Array(count*3); for(let i=0;i<count;i++){ const r=22*Math.cbrt(Math.random()),t=Math.random()*Math.PI*2,p=Math.acos(2*Math.random()-1); pos[i*3]=r*Math.sin(p)*Math.cos(t); pos[i*3+1]=r*Math.cos(p); pos[i*3+2]=r*Math.sin(p)*Math.sin(t); } const geo=new THREE.BufferGeometry(); geo.setAttribute('position',new THREE.BufferAttribute(pos,3)); this.stars=new THREE.Points(geo,new THREE.PointsMaterial({size:.045,color:0x65dfff,transparent:true,opacity:.42,depthWrite:false})); this.scene.add(this.stars); const floor=new THREE.Mesh(new THREE.CircleGeometry(18,96),new THREE.MeshStandardMaterial({color:0x071522,roughness:.65,metalness:.12,transparent:true,opacity:.88})); floor.rotation.x=-Math.PI/2; floor.position.y=-2.05; floor.receiveShadow=true; this.scene.add(floor); const grid=new THREE.GridHelper(36,36,0x2a7ea0,0x143249); grid.position.y=-2; grid.material.opacity=.16; grid.material.transparent=true; this.scene.add(grid); }
  bind(){ addEventListener('resize',()=>this.resize()); this.renderer.domElement.addEventListener('pointermove',(e)=>{ const rect=this.renderer.domElement.getBoundingClientRect(); this.pointer.x=((e.clientX-rect.left)/rect.width)*2-1; this.pointer.y=-((e.clientY-rect.top)/rect.height)*2+1; if(this.robot?.head){ this.robot.head.rotation.y=THREE.MathUtils.lerp(this.robot.head.rotation.y,this.pointer.x*.28,.08); this.robot.head.rotation.x=THREE.MathUtils.lerp(this.robot.head.rotation.x,-this.pointer.y*.12,.08); } }); this.renderer.domElement.addEventListener('click',(e)=>{ const rect=this.renderer.domElement.getBoundingClientRect(); this.pointer.x=((e.clientX-rect.left)/rect.width)*2-1; this.pointer.y=-((e.clientY-rect.top)/rect.height)*2+1; this.raycaster.setFromCamera(this.pointer,this.camera); const hit=this.raycaster.intersectObjects(this.interactive,true)[0]; if(hit){ let object=hit.object; while(object.parent&&!object.userData.action&&object!==this.activeGroup) object=object.parent; object.userData.action?.(); } }); }
  resize(){ const w=this.container.clientWidth||innerWidth,h=this.container.clientHeight||innerHeight,dpr=Math.min(devicePixelRatio,innerWidth<700?1.4:1.8); this.renderer.setPixelRatio(dpr); this.renderer.setSize(w,h,false); this.camera.aspect=w/h; this.camera.updateProjectionMatrix(); }
  clear(){ this.effects=[]; this.interactive=[]; while(this.activeGroup.children.length){ const object=this.activeGroup.children.pop(); object.traverse((node)=>{ node.geometry?.dispose?.(); if(node.material&&!node.material.map) node.material.dispose?.(); }); } this.robot=null; this.networkLayers=null; this.pipelineBlocks=null; this.completePipeline=null; this.attentionNodes=null; this.attentionLines=null; this.trainingBars=null; this.diffusionCells=null; this.generationGroup=null; this.neuronVisual=null; }
  showHome(onEnter){ this.clear(); this.controls.enabled=false; this.camera.position.set(0,.8,9.2); this.controls.target.set(0,.35,0); this.camera.lookAt(0,.3,0); const robot=this.createRobot(); robot.group.position.set(1.9,.1,.1); robot.group.scale.setScalar(1.14); robot.group.userData.action=()=>{ robot.excite=1; this.cameraTween({x:1.9,y:.8,z:3.2},{x:1.9,y:.4,z:0},.7); setTimeout(onEnter,620); }; this.interactive.push(robot.group); this.activeGroup.add(robot.group); const rings=new THREE.Group(); for(let i=0;i<4;i++){ const ring=new THREE.Mesh(new THREE.TorusGeometry(2.25+i*.42,.018,8,100),new THREE.MeshBasicMaterial({color:[COLORS.cyan,COLORS.violet,COLORS.magenta,COLORS.orange][i],transparent:true,opacity:.23})); ring.rotation.x=Math.PI/2+i*.12; rings.add(ring); } rings.position.set(1.9,.4,-.2); this.activeGroup.add(rings); this.effects.push((t)=>{rings.rotation.z=t*.08;robot.group.position.y=.1+Math.sin(t*1.7)*.12;this.animateRobot(robot,t);}); }
  createRobot(){ const group=new THREE.Group(),white=new THREE.MeshStandardMaterial({color:0xe8f8ff,roughness:.23,metalness:.55}),dark=new THREE.MeshStandardMaterial({color:0x0b1830,roughness:.2,metalness:.55}),glow=glowMaterial(COLORS.cyan,2.5); const body=new THREE.Mesh(new THREE.SphereGeometry(1,40,28),white); body.scale.set(1,.95,.7); body.castShadow=true; group.add(body); const core=new THREE.Mesh(new THREE.SphereGeometry(.28,32,24),glow); core.position.set(0,-.1,.72); group.add(core); const coreRing=new THREE.Mesh(new THREE.TorusGeometry(.42,.045,10,48),glowMaterial(COLORS.violet,1.5)); coreRing.position.set(0,-.1,.71); group.add(coreRing); const head=new THREE.Group(); head.position.y=1.2; group.add(head); const skull=new THREE.Mesh(roundedBox(1.45,.95,.65,.3),white); skull.position.set(-.725,-.47,-.32); head.add(skull); const face=new THREE.Mesh(new THREE.PlaneGeometry(1.08,.55),dark); face.position.z=.39; head.add(face); const eyeGeo=new THREE.SphereGeometry(.105,20,12),eyeMat=glowMaterial(COLORS.cyan,4),lEye=new THREE.Mesh(eyeGeo,eyeMat),rEye=new THREE.Mesh(eyeGeo,eyeMat); lEye.position.set(-.27,.03,.43); rEye.position.set(.27,.03,.43); head.add(lEye,rEye); const antenna=new THREE.Mesh(new THREE.CylinderGeometry(.03,.03,.34,12),white); antenna.position.y=.63; head.add(antenna); const tip=new THREE.Mesh(new THREE.SphereGeometry(.09,18,12),glowMaterial(COLORS.magenta,3)); tip.position.y=.83; head.add(tip); const armGeo=new THREE.CapsuleGeometry(.12,.75,6,14),leftArm=new THREE.Mesh(armGeo,white),rightArm=new THREE.Mesh(armGeo,white); leftArm.position.set(-1.02,.1,0); leftArm.rotation.z=-.52; rightArm.position.set(1.02,.1,0); rightArm.rotation.z=.52; group.add(leftArm,rightArm); const shadow=new THREE.Mesh(new THREE.CircleGeometry(1.1,48),new THREE.MeshBasicMaterial({color:0x000000,transparent:true,opacity:.2})); shadow.rotation.x=-Math.PI/2; shadow.position.y=-1.22; group.add(shadow); return this.robot={group,head,eyes:[lEye,rEye],arms:[leftArm,rightArm],core,coreRing,excite:0}; }
  animateRobot(robot,t){ const blink=Math.sin(t*.72)>.985?.1:1; robot.eyes.forEach((eye)=>eye.scale.y=blink); robot.core.scale.setScalar(1+Math.sin(t*3)*.045); robot.coreRing.rotation.z=t*.65; if(robot.excite>.01){ robot.excite*=.94; robot.arms[0].rotation.z=-.52-Math.sin(t*10)*.5*robot.excite; robot.arms[1].rotation.z=.52+Math.sin(t*10)*.5*robot.excite; } }
  showLesson(slug){ this.clear(); this.controls.enabled=true; this.cameraTween({x:0,y:1.2,z:9.2},{x:0,y:.35,z:0},.55); const builders={introduction:()=>this.buildIntro(),'artificial-neuron':()=>this.buildNeuron(),'neural-network':()=>this.buildNetwork(),training:()=>this.buildTraining(),'training-data':()=>this.buildDataWorld(),'machine-learning':()=>this.buildMachineLearning(),'deep-learning':()=>this.buildDeepLearning(),'model-training':()=>this.buildModelTraining(),tokens:()=>this.buildTokens(this.tokenText),embeddings:()=>this.buildEmbeddings(),llm:()=>this.buildLLM(),transformer:()=>this.buildTransformer(),attention:()=>this.buildAttention(),prompt:()=>this.buildPromptPipeline(),generation:()=>this.buildGeneration(),'generative-ai':()=>this.buildGenerativeAI(),'computer-vision':()=>this.buildVision(),'image-generation':()=>this.buildImageGeneration(),hallucinations:()=>this.buildHallucinations(),'ai-pipeline':()=>this.buildCompletePipeline()}; (builders[slug]||builders.introduction)(); this.addMiniRobot(); this.currentSlug=slug; }
  addMiniRobot(){ const robot=this.createRobot(); robot.group.scale.setScalar(.27); robot.group.position.set(3.8,-1.45,1.25); this.activeGroup.add(robot.group); this.effects.push((t)=>{robot.group.position.y=-1.45+Math.sin(t*2)*.05;this.animateRobot(robot,t);}); }
  node(position,color,scale=.36,label=''){ const group=new THREE.Group(); group.position.copy(position); const mesh=new THREE.Mesh(new THREE.SphereGeometry(scale,26,18),glowMaterial(color,1.7)); mesh.castShadow=true; group.add(mesh); if(label){const s=textSprite(label);s.position.y=scale+.38;group.add(s);} this.activeGroup.add(group); return group; }
  block(position,label,color,scale=1){ const group=new THREE.Group(); group.position.copy(position); const mesh=new THREE.Mesh(roundedBox(1.5*scale,.75*scale,.34*scale,.18),glowMaterial(color,.65)); mesh.position.set(-.75*scale,-.375*scale,-.17*scale); mesh.castShadow=true; group.add(mesh); const s=textSprite(label,'#ffffff',26); s.position.z=.25; s.scale.multiplyScalar(.72*scale); group.add(s); this.activeGroup.add(group); return group; }
  buildIntro(){ const labels=['DATA','MODEL','LEARNING','PATTERNS','PREDICTION','OUTPUT'],colors=[COLORS.cyan,COLORS.violet,COLORS.magenta,COLORS.orange,COLORS.lime,COLORS.yellow],nodes=[]; labels.forEach((label,i)=>{ const a=i/labels.length*Math.PI*2-.35,p=new THREE.Vector3(Math.cos(a)*3.2,Math.sin(a)*1.6,Math.sin(a*2)*.6),n=this.node(p,colors[i],.42,label); nodes.push(n); n.userData.action=()=>{n.scale.setScalar(1.28);setTimeout(()=>n.scale.setScalar(1),260);}; this.interactive.push(n); }); for(let i=0;i<nodes.length;i++) this.activeGroup.add(lineBetween(nodes[i].position,nodes[(i+1)%nodes.length].position,colors[i],.35)); const core=this.node(new THREE.Vector3(0,.25,0),COLORS.white,.7,'AI SYSTEM'); nodes.forEach((n,i)=>this.activeGroup.add(lineBetween(n.position,core.position,colors[i],.2))); this.effects.push((t)=>nodes.forEach((n,i)=>n.position.y+=Math.sin(t*1.5+i)*.0018)); }
  buildNeuron(){ const inputA=this.node(new THREE.Vector3(-3.5,1,0),COLORS.cyan,.42,'INPUT A'),inputB=this.node(new THREE.Vector3(-3.5,-1,0),COLORS.violet,.42,'INPUT B'),sum=this.node(new THREE.Vector3(-.4,0,0),COLORS.magenta,.65,'Σ + BIAS'),activation=this.block(new THREE.Vector3(1.65,0,0),'ACTIVATION',COLORS.orange,.95),output=this.node(new THREE.Vector3(3.6,0,0),COLORS.lime,.5,'OUTPUT'); this.activeGroup.add(lineBetween(inputA.position,sum.position,COLORS.cyan,.7),lineBetween(inputB.position,sum.position,COLORS.violet,.7),lineBetween(sum.position,activation.position,COLORS.magenta,.7),lineBetween(activation.position,output.position,COLORS.lime,.7)); this.neuronVisual={inputA,inputB,sum,activation,output}; this.updateNeuronVisual(); }
  setNeuronParams(params){ this.neuronParams={...this.neuronParams,...params}; this.updateNeuronVisual(); }
  updateNeuronVisual(){ if(!this.neuronVisual)return; const p=this.neuronParams,sum=p.inputA*p.weightA+p.inputB*p.weightB+p.bias,out=1/(1+Math.exp(-sum)); this.neuronVisual.inputA.scale.setScalar(.82+p.inputA*.35); this.neuronVisual.inputB.scale.setScalar(.82+p.inputB*.35); this.neuronVisual.sum.rotation.z=sum*.18; this.neuronVisual.output.scale.setScalar(.72+out*.75); const old=this.neuronVisual.output.children.find((c)=>c.userData.valueLabel); if(old)this.neuronVisual.output.remove(old); const label=textSprite(`y = ${out.toFixed(3)}`,'#8dff72',26); label.position.set(0,-.95,0); label.userData.valueLabel=true; this.neuronVisual.output.add(label); }
  buildNetwork(options={}){ const layers=options.deep?[5,7,8,7,5,3]:[4,6,5,3],spacing=options.deep?1.5:2.35,startX=-(layers.length-1)*spacing/2,nodeLayers=[]; layers.forEach((count,li)=>{ const layer=[]; for(let i=0;i<count;i++){ const y=(i-(count-1)/2)*(options.deep?.62:.82),z=Math.sin(i*1.8+li)*.35; layer.push(this.node(new THREE.Vector3(startX+li*spacing,y,z),[COLORS.cyan,COLORS.violet,COLORS.magenta,COLORS.orange,COLORS.lime,COLORS.yellow][li%6],options.deep?.18:.24)); } nodeLayers.push(layer); }); for(let l=0;l<nodeLayers.length-1;l++) nodeLayers[l].forEach((a)=>nodeLayers[l+1].forEach((b)=>this.activeGroup.add(lineBetween(a.position,b.position,0x6f86b9,options.deep?.08:.13)))); this.networkLayers=nodeLayers; if(!options.noIdle)this.effects.push((t)=>nodeLayers.flat().forEach((n,i)=>n.scale.setScalar(.94+Math.sin(t*2+i)*.06))); }
  buildTraining(){ this.buildNetwork({noIdle:true}); const label=textSprite('PREDICTION → ERROR → BACKPROPAGATION','#ffbf72',26); label.position.set(0,3.15,0); this.activeGroup.add(label); }
  buildDataWorld(){ const types=[['TEXT','Aa',COLORS.cyan],['IMAGE','▧',COLORS.magenta],['AUDIO','♪',COLORS.orange],['VIDEO','▶',COLORS.violet],['NUMBERS','123',COLORS.lime],['SENSORS','⌁',COLORS.yellow]]; types.forEach(([name,icon,color],i)=>{ const a=i/types.length*Math.PI*2,b=this.block(new THREE.Vector3(Math.cos(a)*3.4,Math.sin(a)*1.8,Math.sin(a*2)*.7),`${icon}  ${name}`,color,.82); b.rotation.y=-a+Math.PI/2; }); const trainer=this.block(new THREE.Vector3(0,0,0),'TRAINING SYSTEM',COLORS.white,1.12); this.effects.push((t)=>trainer.rotation.y=Math.sin(t*.6)*.12); }
  buildMachineLearning(){ const centers=[new THREE.Vector3(-2.6,.7,0),new THREE.Vector3(0,-.8,.2),new THREE.Vector3(2.6,.65,-.2)],colors=[COLORS.cyan,COLORS.magenta,COLORS.lime]; centers.forEach((center,cluster)=>{ for(let i=0;i<14;i++) this.node(center.clone().add(new THREE.Vector3((Math.random()-.5)*1.45,(Math.random()-.5)*1.45,(Math.random()-.5)*1.4)),colors[cluster],.085); const l=textSprite(['SUPERVISED','UNSUPERVISED','REINFORCEMENT'][cluster],'#ffffff',21); l.position.copy(center).add(new THREE.Vector3(0,1.4,0)); this.activeGroup.add(l); }); const agent=this.node(new THREE.Vector3(2.6,-.65,1),COLORS.yellow,.2,'AGENT'); this.effects.push((t)=>{agent.position.x=2.6+Math.sin(t*1.3)*1.2;agent.position.z=Math.cos(t*1.3)*.9;}); }
  buildDeepLearning(){ this.buildNetwork({deep:true}); }
  buildModelTraining(){ const bars=[]; for(let i=0;i<12;i++){ const h=.35+(1-Math.exp(-i/4))*2.2,mesh=new THREE.Mesh(new THREE.BoxGeometry(.32,h,.48),glowMaterial(new THREE.Color().setHSL(.5+i/60,.8,.55).getHex(),.4)); mesh.position.set(-3.1+i*.56,-1.5+h/2,0); this.activeGroup.add(mesh); bars.push(mesh); } const top=textSprite('MODEL QUALITY ↑','#8dff72',26); top.position.set(0,2.2,0); this.activeGroup.add(top); const loss=textSprite('LOSS ↓','#ff8fb8',24); loss.position.set(0,-2,0); this.activeGroup.add(loss); this.trainingBars=bars; }
  buildTokens(text){ this.tokenText=text; const raw=text.trim().match(/[\p{L}\p{N}]+|[^\s\p{L}\p{N}]/gu)||[],tokens=raw.slice(0,14),colors=[COLORS.cyan,COLORS.violet,COLORS.magenta,COLORS.orange,COLORS.lime,COLORS.yellow]; tokens.forEach((token,i)=>{ const x=(i%5-2)*1.55,y=1.45-Math.floor(i/5)*1.15,block=this.block(new THREE.Vector3(x,y,Math.sin(i)*.35),token,colors[i%colors.length],.78); }); const count=textSprite(`${tokens.length} simplified token${tokens.length===1?'':'s'}`,'#bfefff',24); count.position.set(0,-2,0); this.activeGroup.add(count); }
  setTokenText(text){ this.clear(); this.buildTokens(text||'AI'); this.addMiniRobot(); this.currentSlug='tokens'; }
  buildEmbeddings(){ const data=[['King',-2.3,1.1,.2,COLORS.violet],['Queen',-1.65,1.35,.15,COLORS.magenta],['Man',-2.1,.2,-.2,COLORS.blue],['Woman',-1.45,.4,-.15,COLORS.cyan],['Car',1.25,1.2,.15,COLORS.orange],['Truck',2.05,1,-.1,COLORS.yellow],['Cat',.8,-.9,.4,COLORS.lime],['Dog',1.55,-.75,.15,COLORS.cyan]]; data.forEach(([word,x,y,z,c])=>{ const n=this.node(new THREE.Vector3(x,y,z),c,.18,word); n.userData.action=()=>{n.scale.setScalar(1.6);setTimeout(()=>n.scale.setScalar(1),350);}; this.interactive.push(n); }); const label=textSprite('SIMPLIFIED 3D VIEW OF A HIGH-DIMENSIONAL IDEA','#9fb9ca',17); label.position.set(0,-2.15,0); this.activeGroup.add(label); }
  buildLLM(){ this.buildNetwork({deep:true,noIdle:true}); this.block(new THREE.Vector3(-4.6,2.4,0),'“The sky is…”',COLORS.cyan,.8); [['blue 72%',COLORS.cyan],['clear 12%',COLORS.lime],['beautiful 7%',COLORS.magenta],['dark 5%',COLORS.violet]].forEach(([t,c],i)=>this.block(new THREE.Vector3(3.7,1.8-i*.85,.2),t,c,.68)); }
  buildTransformer(){ const stages=[['TOKEN INPUT',COLORS.cyan],['EMBEDDING',COLORS.blue],['POSITION',COLORS.violet],['ATTENTION',COLORS.magenta],['FEED FORWARD',COLORS.orange],['OUTPUT',COLORS.lime]]; stages.forEach(([label,color],i)=>{ const y=2.25-i*.9,b=this.block(new THREE.Vector3(0,y,0),label,color,.92); b.userData.action=()=>this.cameraTween({x:0,y,z:5.2},{x:0,y,z:0},.35); this.interactive.push(b); }); }
  buildAttention(){ const words=['The','robot','picked','up','the','ball','because','it','was','red']; this.attentionNodes=words.map((word,i)=>{ const x=(i-(words.length-1)/2)*.82,y=Math.sin(i*.8)*.42,n=this.node(new THREE.Vector3(x,y,0),i===7?COLORS.magenta:COLORS.cyan,.17,word); n.userData.action=()=>this.focusAttention(i); this.interactive.push(n); return n; }); this.focusAttention(7); }
  focusAttention(index){ if(!this.attentionNodes)return; this.attentionLines?.forEach((line)=>{this.activeGroup.remove(line);line.geometry.dispose();line.material.dispose();}); const focus=this.attentionNodes[index]; this.attentionLines=this.attentionNodes.map((n,i)=>{ if(i===index)return null; const dist=Math.abs(i-index),semanticBoost=(index===7&&[1,5,9].includes(i))?.75:0,strength=Math.min(.95,.12+1/(dist+1)+semanticBoost),line=lineBetween(focus.position,n.position,strength>.55?COLORS.magenta:COLORS.violet,strength); this.activeGroup.add(line); return line; }).filter(Boolean); this.attentionNodes.forEach((n,i)=>n.scale.setScalar(i===index?1.6:1)); }
  buildPromptPipeline(){ const labels=['USER PROMPT','TOKENIZATION','EMBEDDINGS','TRANSFORMER','ATTENTION','NEXT TOKEN','RESPONSE'],colors=[COLORS.cyan,COLORS.blue,COLORS.violet,COLORS.magenta,COLORS.orange,COLORS.yellow,COLORS.lime]; this.pipelineBlocks=labels.map((label,i)=>this.block(new THREE.Vector3((i-3)*1.28,Math.sin((i/6)*Math.PI)*.8-.2,0),label,colors[i],.64)); for(let i=1;i<this.pipelineBlocks.length;i++) this.activeGroup.add(lineBetween(this.pipelineBlocks[i-1].position,this.pipelineBlocks[i].position,colors[i],.4)); }
  runPrompt(text){ if(this.currentSlug==='prompt'){this.promptText=text;this.animatePipeline();} }
  buildGeneration(){ this.block(new THREE.Vector3(0,2.25,0),'Explain gravity simply.',COLORS.cyan,.82); this.generationGroup=new THREE.Group(); this.activeGroup.add(this.generationGroup); const label=textSprite('TOKEN-BY-TOKEN GENERATION','#d7f6ff',23); label.position.set(0,-2,0); this.activeGroup.add(label); }
  buildGenerativeAI(){ const items=[['TEXT','Aa',COLORS.cyan],['IMAGE','◩',COLORS.magenta],['AUDIO','♪',COLORS.orange],['VIDEO','▶',COLORS.violet],['3D','⬡',COLORS.lime]]; items.forEach(([name,icon,c],i)=>{ const a=i/items.length*Math.PI*2+Math.PI/2,portal=new THREE.Mesh(new THREE.TorusGeometry(.72,.11,14,64),glowMaterial(c,2)); portal.position.set(Math.cos(a)*3.1,Math.sin(a)*1.6,0); portal.rotation.y=.4; this.activeGroup.add(portal); const s=textSprite(`${icon} ${name}`,'#ffffff',24); s.position.copy(portal.position).add(new THREE.Vector3(0,-1.05,0)); this.activeGroup.add(s); this.effects.push((t)=>portal.rotation.z=t*(.22+i*.03)); }); }
  buildVision(){ const screen=new THREE.Mesh(new THREE.PlaneGeometry(6.8,4.1),new THREE.MeshStandardMaterial({color:0x16324a,roughness:.7,metalness:.1})); screen.position.z=-.3; this.activeGroup.add(screen); [['PERSON',-2,.45,1,2.1,COLORS.cyan],['CAR',.8,-.75,2.4,1.05,COLORS.orange],['CAT',2.1,.62,1,.95,COLORS.magenta],['CHAIR',-.4,-.8,1.1,1.2,COLORS.lime]].forEach(([label,x,y,w,h,c])=>{ const edges=new THREE.LineSegments(new THREE.EdgesGeometry(new THREE.PlaneGeometry(w,h)),new THREE.LineBasicMaterial({color:c})); edges.position.set(x,y,0); this.activeGroup.add(edges); const s=textSprite(`${label} ${Math.floor(82+Math.random()*15)}%`,'#ffffff',18); s.position.set(x,y+h/2+.22,.02); s.scale.multiplyScalar(.72); this.activeGroup.add(s); }); }
  buildImageGeneration(){ const group=new THREE.Group(); this.activeGroup.add(group); this.diffusionCells=[]; const size=15; for(let x=0;x<size;x++)for(let y=0;y<size;y++){ const m=new THREE.Mesh(new THREE.BoxGeometry(.24,.24,.13),new THREE.MeshStandardMaterial({color:Math.random()*0xffffff,roughness:.75,emissive:0x061018})); m.position.set((x-size/2)*.26,(y-size/2)*.26,Math.random()*.22); group.add(m); this.diffusionCells.push({mesh:m,x,y,noise:Math.random()}); } const start=textSprite('RANDOM NOISE','#d7f6ff',22); start.position.set(-3.1,-2.25,0); this.activeGroup.add(start); const end=textSprite('STRUCTURE','#8dff72',22); end.position.set(3.1,-2.25,0); this.activeGroup.add(end); this.setDenoise(0); }
  setDenoise(v){ this.denoise=v; this.diffusionCells?.forEach(({mesh,x,y,noise})=>{ const nx=x/14-.5,ny=y/14-.5,face=Math.exp(-((nx*1.2)**2+(ny*1.1)**2)*3.2),eye=Math.max(0,1-Math.hypot(Math.abs(nx)-.18,ny-.1)*8),mouth=Math.max(0,1-Math.abs(ny+.17)*15)*Math.max(0,1-Math.abs(nx)*3),target=new THREE.Color().setHSL(.52+face*.12+mouth*.2,.68,.26+face*.4+eye*.25),random=new THREE.Color().setHSL(noise,.85,.55); mesh.material.color.copy(random.lerp(target,v)); mesh.position.z=(1-v)*(noise-.5)*.45+v*face*.3; }); }
  buildHallucinations(){ [['Supported answer',COLORS.lime,'VERIFIED'],['Plausible but wrong',COLORS.magenta,'CHECK'],['Uncertain answer',COLORS.orange,'LOW EVIDENCE']].forEach(([label,c,tag],i)=>{ const y=1.35-i*1.35,b=this.block(new THREE.Vector3(0,y,0),label,c,1.1),s=textSprite(tag,i===0?'#8dff72':'#ffba75',19); s.position.set(0,y-.65,0); this.activeGroup.add(s); b.userData.action=()=>b.rotation.z+=.12; this.interactive.push(b); }); }
  buildCompletePipeline(){ const labels=['TRAINING DATA','TOKENIZATION','EMBEDDINGS','NEURAL NETWORK','TRANSFORMER','ATTENTION','PARAMETERS','PROMPT','TOKEN PREDICTION','RESPONSE'],colors=[COLORS.cyan,COLORS.blue,COLORS.violet,COLORS.magenta,COLORS.orange,COLORS.yellow,COLORS.lime,COLORS.cyan,COLORS.magenta,COLORS.lime],radius=3.4; this.completePipeline=labels.map((label,i)=>{ const a=i/labels.length*Math.PI*2-Math.PI/2,p=new THREE.Vector3(Math.cos(a)*radius,Math.sin(a)*1.85,Math.sin(a*2)*.5),b=this.block(p,label,colors[i],.58); return b; }); this.completePipeline.forEach((b,i)=>this.activeGroup.add(lineBetween(b.position,this.completePipeline[(i+1)%this.completePipeline.length].position,colors[i],.36))); const core=this.node(new THREE.Vector3(0,0,0),COLORS.white,.62,'AI SYSTEM'); this.effects.push((t)=>core.rotation.y=t*.3); }
  handleAction(action,payload){ if(action==='denoise')return this.setDenoise(payload); if(action==='speed'){this.generationSpeed=payload;return;} if(action==='generate')return this.animateGeneration(); if(action!=='run')return; switch(payload){ case'neural-network':case'training':case'llm':this.animateNetwork(payload==='training');break; case'model-training':this.animateTrainingBars();break; case'attention':this.focusAttention(Math.floor(Math.random()*this.attentionNodes.length));break; case'prompt':this.animatePipeline();break; case'image-generation':this.setDenoise((this.denoise+.2)%1.01);break; case'ai-pipeline':this.animateCompletePipeline();break; default:this.pulseScene(); } }
  animateNetwork(backward=false){ if(!this.networkLayers)return; const layers=backward?[...this.networkLayers].reverse():this.networkLayers; layers.forEach((layer,li)=>setTimeout(()=>layer.forEach((n)=>{ n.children[0].material.emissiveIntensity=5; n.scale.setScalar(1.45); setTimeout(()=>{n.children[0].material.emissiveIntensity=1.7;n.scale.setScalar(1);},260);}),li*360)); }
  animateTrainingBars(){ this.trainingBars?.forEach((bar,i)=>{bar.scale.y=.08;setTimeout(()=>bar.scale.y=1,i*90);}); }
  animatePipeline(){ this.pipelineBlocks?.forEach((block,i)=>setTimeout(()=>{block.scale.setScalar(1.28);setTimeout(()=>block.scale.setScalar(1),270);},i*260)); }
  animateGeneration(){ if(!this.generationGroup)return; this.generationGroup.clear(); const tokens=['Gravity','is','the','pull','that','brings','objects','toward','each','other.']; tokens.forEach((token,i)=>setTimeout(()=>{ const group=new THREE.Group(),mesh=new THREE.Mesh(roundedBox(.95,.48,.22,.12),glowMaterial([COLORS.cyan,COLORS.violet,COLORS.magenta,COLORS.orange,COLORS.lime][i%5],.65)); mesh.position.set(-.475,-.24,-.11); group.add(mesh); const s=textSprite(token,'#ffffff',21); s.position.z=.17; s.scale.multiplyScalar(.55); group.add(s); group.position.set((i%5-2)*1.1,.75-Math.floor(i/5)*.9,.15); this.generationGroup.add(group); },i*(420/this.generationSpeed))); }
  animateCompletePipeline(){ this.completePipeline?.forEach((b,i)=>setTimeout(()=>{b.scale.setScalar(1.32);setTimeout(()=>b.scale.setScalar(1),250);},i*180)); }
  pulseScene(){ this.activeGroup.children.forEach((o,i)=>setTimeout(()=>{if(o.scale){const s=o.scale.clone();o.scale.multiplyScalar(1.06);setTimeout(()=>o.scale.copy(s),180);}},i*20)); }
  cameraTween(position,target,duration=.6){ const from=this.camera.position.clone(),to=new THREE.Vector3(position.x,position.y,position.z),targetFrom=this.controls.target.clone(),targetTo=new THREE.Vector3(target.x,target.y,target.z),start=performance.now(); const move=(now)=>{ const p=Math.min(1,(now-start)/(duration*1000)),ease=1-Math.pow(1-p,3); this.camera.position.lerpVectors(from,to,ease); this.controls.target.lerpVectors(targetFrom,targetTo,ease); this.camera.lookAt(this.controls.target); if(p<1)requestAnimationFrame(move); }; requestAnimationFrame(move); }
  setSound(enabled){ this.sound=enabled; }
  animate(){ this.raf=requestAnimationFrame(()=>this.animate()); const t=this.clock.getElapsedTime(); this.controls.update(); if(this.stars)this.stars.rotation.y=t*.006; this.effects.forEach((effect)=>effect(t)); this.renderer.render(this.scene,this.camera); }
  dispose(){ cancelAnimationFrame(this.raf); this.controls.dispose(); this.renderer.dispose(); }
}
