import './styles.css';
import * as THREE from 'three';

const lessons = [
  ['introduction','AI Basics','What Is Artificial Intelligence?','هوش مصنوعی چیست؟','AI systems learn statistical patterns from data and use those patterns to make predictions, decisions, or generate new outputs.','سامانه‌های هوش مصنوعی از داده‌ها الگوهای آماری را یاد می‌گیرند و از آن‌ها برای پیش‌بینی، تصمیم‌گیری یا تولید خروجی جدید استفاده می‌کنند.'],
  ['artificial-neuron','Neural Networks','Artificial Neurons','نورون‌های مصنوعی','An artificial neuron combines inputs, weights and a bias, then applies an activation function to produce an output.','نورون مصنوعی ورودی‌ها، وزن‌ها و بایاس را ترکیب می‌کند و سپس با تابع فعال‌سازی یک خروجی می‌سازد.'],
  ['neural-network','Neural Networks','Neural Networks','شبکه‌های عصبی','Neural networks connect many artificial neurons in layers so information can be transformed step by step.','شبکه عصبی تعداد زیادی نورون مصنوعی را در لایه‌ها به هم متصل می‌کند تا اطلاعات مرحله‌به‌مرحله تبدیل شوند.'],
  ['training','Learning','How AI Learns','هوش مصنوعی چگونه یاد می‌گیرد؟','During training, the model predicts, measures error and updates its parameters to reduce future error.','در آموزش، مدل پیش‌بینی می‌کند، خطا را اندازه می‌گیرد و پارامترهایش را برای کاهش خطا به‌روزرسانی می‌کند.'],
  ['training-data','Learning','Training Data','داده‌های آموزشی','Training data provides examples from which an AI system can learn useful statistical structure.','داده‌های آموزشی نمونه‌هایی فراهم می‌کنند که هوش مصنوعی از آن‌ها ساختار و الگوهای مفید را یاد می‌گیرد.'],
  ['machine-learning','Learning','Machine Learning','یادگیری ماشین','Machine learning includes supervised, unsupervised and reinforcement-learning approaches.','یادگیری ماشین شامل روش‌های نظارت‌شده، بدون‌نظارت و یادگیری تقویتی است.'],
  ['deep-learning','Neural Networks','Deep Learning','یادگیری عمیق','Deep learning uses multi-layer neural networks to build increasingly rich internal representations.','یادگیری عمیق از شبکه‌های چندلایه برای ساخت نمایش‌های داخلی پیچیده‌تر استفاده می‌کند.'],
  ['model-training','Learning','AI Model Training','آموزش مدل هوش مصنوعی','Model training repeatedly compares predictions with an objective and adjusts millions or billions of parameters.','آموزش مدل بارها پیش‌بینی را با هدف آموزشی مقایسه می‌کند و تعداد زیادی پارامتر را تنظیم می‌کند.'],
  ['tokens','Language Models','Tokens','توکن‌ها','Language models read text as tokens: words, word pieces, punctuation and other small units.','مدل‌های زبانی متن را به شکل توکن‌ها می‌خوانند؛ یعنی کلمه، بخشی از کلمه، نشانه و واحدهای کوچک دیگر.'],
  ['embeddings','Language Models','Embeddings','امبدینگ‌ها','Embeddings turn tokens and concepts into vectors in a high-dimensional numerical space.','امبدینگ‌ها توکن‌ها و مفاهیم را به بردارهایی در یک فضای عددی چندبعدی تبدیل می‌کنند.'],
  ['llm','Language Models','Large Language Models','مدل‌های زبانی بزرگ','LLMs process token sequences and repeatedly predict a distribution over possible next tokens.','مدل‌های زبانی بزرگ دنباله توکن‌ها را پردازش می‌کنند و احتمال توکن بعدی را پیش‌بینی می‌کنند.'],
  ['transformer','Language Models','Transformers','ترنسفورمرها','Transformers combine attention, feed-forward layers, residual connections and positional information.','ترنسفورمرها Attention، لایه‌های پیش‌خور، اتصال‌های باقیمانده و اطلاعات موقعیتی را ترکیب می‌کنند.'],
  ['attention','Language Models','Attention Mechanism','مکانیزم توجه','Attention lets the model dynamically weigh which parts of the context are most relevant to each token.','Attention به مدل کمک می‌کند تشخیص دهد کدام بخش‌های زمینه برای هر توکن مهم‌تر هستند.'],
  ['prompt','Language Models','How AI Understands a Prompt','هوش مصنوعی چگونه پرامپت را پردازش می‌کند؟','A prompt is tokenized, embedded and processed through many layers to build context-sensitive hidden states.','پرامپت توکن‌سازی و امبد می‌شود و از لایه‌های متعدد عبور می‌کند تا نمایش‌های وابسته به زمینه ساخته شوند.'],
  ['generation','Language Models','How AI Generates an Answer','هوش مصنوعی چگونه پاسخ تولید می‌کند؟','Text is generated token by token; each selected token becomes part of the context for the next prediction.','متن توکن‌به‌توکن تولید می‌شود و هر توکن انتخاب‌شده وارد زمینه پیش‌بینی بعدی می‌شود.'],
  ['generative-ai','Generative AI','Generative AI','هوش مصنوعی مولد','Generative AI models synthesize new text, images, audio, video or 3D content from learned patterns.','هوش مصنوعی مولد بر اساس الگوهای آموخته‌شده متن، تصویر، صدا، ویدئو یا محتوای سه‌بعدی جدید می‌سازد.'],
  ['computer-vision','AI Vision','Computer Vision','بینایی ماشین','Computer vision systems transform pixels into features used for classification, detection, segmentation and understanding.','سامانه‌های بینایی ماشین پیکسل‌ها را به ویژگی‌هایی برای طبقه‌بندی، تشخیص، قطعه‌بندی و درک تصویر تبدیل می‌کنند.'],
  ['image-generation','Generative AI','AI Image Generation','تولید تصویر با هوش مصنوعی','Many image generators use diffusion: they gradually transform noise into a structured image guided by learned patterns.','بسیاری از مولدهای تصویر از Diffusion استفاده می‌کنند و نویز را مرحله‌به‌مرحله به تصویر ساختاریافته تبدیل می‌کنند.'],
  ['hallucinations','AI Basics','AI Hallucinations','هذیان‌های هوش مصنوعی','Generative models can produce fluent but incorrect claims because plausibility is not the same as verification.','مدل‌های مولد ممکن است پاسخ روان اما نادرست بسازند؛ چون محتمل‌بودن با راستی‌آزمایی یکسان نیست.'],
  ['ai-pipeline','AI Pipeline','Complete AI Pipeline','مسیر کامل هوش مصنوعی','A complete AI pipeline connects data, training, learned parameters, input processing, inference and final output.','یک مسیر کامل هوش مصنوعی داده، آموزش، پارامترهای آموخته‌شده، پردازش ورودی، استنتاج و خروجی را به هم متصل می‌کند.']
].map((x,i)=>({slug:x[0],category:x[1],number:i+1,title:{en:x[2],fa:x[3]},basic:{en:x[4],fa:x[5]}}));

const categoryFA = {'AI Basics':'مبانی هوش مصنوعی','Neural Networks':'شبکه‌های عصبی','Learning':'یادگیری','Language Models':'مدل‌های زبانی','Generative AI':'هوش مصنوعی مولد','AI Vision':'بینایی ماشین','AI Pipeline':'مسیر هوش مصنوعی'};
const copy = {
  en:{journey:'YOUR AI JOURNEY',explore:'EXPLORE',map:'AI Lab Map',museum:'INTERACTIVE 3D AI MUSEUM',hero:'See how <span>AI</span><br>actually works.',desc:'Explore neurons, training, tokens, transformers, attention, generation and more inside an animated 3D AI laboratory.',enter:'Enter the AI Lab →',click:'Click the 3D robot',ready:'Your AI guide is ready',basic:'Basic',details:'More details',advanced:'Advanced',tip:'Drag the scene to look around. Use the menu to explore all 20 lessons.',previous:'Previous',next:'Next',mark:'Mark complete ✓',completed:'Completed ✓'},
  fa:{journey:'مسیر یادگیری شما',explore:'کاوش',map:'نقشه آزمایشگاه هوش مصنوعی',museum:'موزه تعاملی سه‌بعدی هوش مصنوعی',hero:'ببینید <span>هوش مصنوعی</span><br>واقعاً چگونه کار می‌کند.',desc:'نورون‌ها، آموزش، توکن‌ها، ترنسفورمر، Attention، تولید محتوا و مفاهیم دیگر را در یک آزمایشگاه سه‌بعدی انیمیشنی کشف کنید.',enter:'ورود به آزمایشگاه ←',click:'روی ربات سه‌بعدی کلیک کنید',ready:'راهنمای هوش مصنوعی آماده است',basic:'ساده',details:'جزئیات بیشتر',advanced:'پیشرفته',tip:'برای مشاهده بهتر صحنه را با ماوس حرکت دهید و از منو بین ۲۰ درس جابه‌جا شوید.',previous:'قبلی',next:'بعدی',mark:'تکمیل درس ✓',completed:'تکمیل شده ✓'}
};

let lang = localStorage.getItem('how-ai-works-language') === 'fa' ? 'fa' : 'en';
let current = -1;
let level = 'basic';
let savedProgress=[];
try{savedProgress=JSON.parse(localStorage.getItem('how-ai-works-progress')||'[]');if(!Array.isArray(savedProgress))savedProgress=[];}catch{savedProgress=[];}
const progress = new Set(savedProgress);

document.documentElement.lang = lang;
document.documentElement.dir = lang === 'fa' ? 'rtl' : 'ltr';

const root = document.querySelector('#app');
root.innerHTML = `<main class="app-shell"><div id="stage" class="stage"></div><div id="ui"></div><div id="fallback" class="fallback" hidden><h2>3D mode unavailable</h2><p>The educational content is still available.</p></div></main>`;

const stage = document.querySelector('#stage');
const uiRoot = document.querySelector('#ui');
const fallback = document.querySelector('#fallback');
function c(k){ return copy[lang][k]; }
function titleOf(l){ return l.title[lang]; }
function categoryOf(l){ return lang==='fa' ? (categoryFA[l.category]||l.category) : l.category; }

function renderUI(){
  uiRoot.innerHTML = `<header class="topbar glass"><button class="brand" id="homeBtn"><span class="brand-orb"></span><b>HOW AI WORKS</b></button><div class="journey"><span>${c('journey')}</span><strong id="progressText">${progress.size}/20</strong><i><em style="width:${progress.size/20*100}%"></em></i></div><div class="top-actions"><div class="language-switch"><button data-lang="en" class="${lang==='en'?'active':''}">EN</button><button data-lang="fa" class="${lang==='fa'?'active':''}">فا</button></div><button class="icon-btn" id="menuBtn">☰</button></div></header><aside class="lesson-drawer glass" id="drawer"><div class="drawer-head"><div><p class="eyebrow">${c('explore')}</p><h2>${c('map')}</h2></div><button class="icon-btn" id="closeDrawer">×</button></div><div id="lessonList" class="lesson-list"></div></aside><section id="homeUI" class="home-ui" ${current>=0?'hidden':''}><div class="hero-copy"><p class="eyebrow pill">${c('museum')}</p><h1>${c('hero')}</h1><p>${c('desc')}</p><button class="primary" id="enterBtn">${c('enter')}</button><div class="hero-meta"><span>20 interactive lessons</span><span>Real-time WebGL</span><span>English / فارسی</span></div></div><div class="robot-hint glass"><span class="pulse-dot"></span><b>${c('click')}</b><small>${c('ready')}</small></div></section><section id="lessonUI" class="lesson-ui" ${current<0?'hidden':''}><div class="lesson-heading"><p class="eyebrow" id="lessonCategory"></p><h1 id="lessonTitle"></h1><p id="lessonBasic"></p><div class="level-tabs"><button data-level="basic" class="${level==='basic'?'active':''}">${c('basic')}</button><button data-level="details" class="${level==='details'?'active':''}">${c('details')}</button><button data-level="advanced" class="${level==='advanced'?'active':''}">${c('advanced')}</button></div></div><div class="lesson-tip glass"><span>TIP</span><p>${c('tip')}</p></div><div class="lesson-nav glass"><button id="prevBtn">← <span>${c('previous')}</span></button><button id="completeBtn" class="complete-btn"></button><button id="nextBtn"><span>${c('next')}</span> →</button></div></section>`;
  const drawer = document.querySelector('#drawer');
  document.querySelector('#menuBtn').onclick=()=>drawer.classList.add('open');
  document.querySelector('#closeDrawer').onclick=()=>drawer.classList.remove('open');
  document.querySelector('#homeBtn').onclick=()=>showHome();
  document.querySelector('#enterBtn')?.addEventListener('click',()=>openLesson(0));
  document.querySelectorAll('[data-lang]').forEach(b=>b.onclick=()=>{lang=b.dataset.lang;localStorage.setItem('how-ai-works-language',lang);document.documentElement.lang=lang;document.documentElement.dir=lang==='fa'?'rtl':'ltr';renderUI();if(current>=0)updateLessonUI();});
  document.querySelectorAll('[data-level]').forEach(b=>b.onclick=()=>{level=b.dataset.level;renderUI();if(current>=0)updateLessonUI();});
  renderLessonList(); if(current>=0)updateLessonUI();
}

function renderLessonList(){
  const list=document.querySelector('#lessonList');
  const cats=[...new Set(lessons.map(l=>l.category))];
  list.innerHTML=cats.map(cat=>`<div class="lesson-group"><p>${lang==='fa'?(categoryFA[cat]||cat):cat}</p>${lessons.filter(l=>l.category===cat).map(l=>`<button class="lesson-link" data-index="${l.number-1}"><span>${String(l.number).padStart(2,'0')}</span><b>${titleOf(l)}</b><i>${progress.has(l.slug)?'✓':'→'}</i></button>`).join('')}</div>`).join('');
  list.querySelectorAll('[data-index]').forEach(b=>b.onclick=()=>{document.querySelector('#drawer').classList.remove('open');openLesson(Number(b.dataset.index));});
}

function detailText(l){if(level==='basic')return l.basic[lang];if(level==='details')return lang==='fa'?`${l.basic.fa} این بخش با یک شبیه‌سازی سه‌بعدی ساده نشان می‌دهد اطلاعات چگونه میان اجزای مختلف جریان پیدا می‌کند.`:`${l.basic.en} This section uses a simplified 3D simulation to show how information moves through the system.`;return lang==='fa'?`${l.basic.fa} در سامانه‌های واقعی، معماری، داده، تابع هدف و پارامترهای آموخته‌شده همگی روی رفتار نهایی مدل اثر می‌گذارند.`:`${l.basic.en} In real systems, architecture, data, training objectives and learned parameters all influence final behavior.`;}
function updateLessonUI(){const l=lessons[current];if(!l)return;document.querySelector('#lessonCategory').textContent=`${String(l.number).padStart(2,'0')} / ${categoryOf(l)}`;document.querySelector('#lessonTitle').textContent=titleOf(l);document.querySelector('#lessonBasic').textContent=detailText(l);const prev=document.querySelector('#prevBtn'),next=document.querySelector('#nextBtn'),complete=document.querySelector('#completeBtn');prev.disabled=current===0;next.disabled=current===lessons.length-1;prev.onclick=()=>current>0&&openLesson(current-1);next.onclick=()=>current<lessons.length-1&&openLesson(current+1);complete.textContent=progress.has(l.slug)?c('completed'):c('mark');complete.classList.toggle('done',progress.has(l.slug));complete.onclick=()=>{progress.has(l.slug)?progress.delete(l.slug):progress.add(l.slug);localStorage.setItem('how-ai-works-progress',JSON.stringify([...progress]));renderUI();};}
function showHome(){current=-1;location.hash='#/';renderUI();buildHomeScene();}
function openLesson(i){current=Math.max(0,Math.min(lessons.length-1,i));renderUI();buildLessonScene(current);location.hash=`#/${lessons[current].slug}`;}

let renderer,scene,camera,robot,vizGroup,raycaster,pointer,mouseX=0,mouseY=0;
const robotParts={};
function init3D(){try{renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));renderer.setSize(innerWidth,innerHeight);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.15;stage.appendChild(renderer.domElement);scene=new THREE.Scene();scene.background=new THREE.Color(0x050b18);scene.fog=new THREE.FogExp2(0x07121f,.032);camera=new THREE.PerspectiveCamera(46,innerWidth/innerHeight,.1,100);camera.position.set(0,.8,9);scene.add(new THREE.HemisphereLight(0xb8f3ff,0x120826,2.2));const key=new THREE.DirectionalLight(0xffffff,3.2);key.position.set(4,7,5);scene.add(key);const cyan=new THREE.PointLight(0x35efff,18,18);cyan.position.set(-4,2,4);scene.add(cyan);const pink=new THREE.PointLight(0xff4fc8,14,16);pink.position.set(4,1,2);scene.add(pink);const grid=new THREE.GridHelper(36,36,0x2a7ea0,0x143249);grid.position.y=-2;grid.material.transparent=true;grid.material.opacity=.15;scene.add(grid);const starGeo=new THREE.BufferGeometry(),count=180,pos=new Float32Array(count*3);for(let i=0;i<count;i++){pos[i*3]=(Math.random()-.5)*24;pos[i*3+1]=(Math.random()-.5)*14;pos[i*3+2]=-Math.random()*18;}starGeo.setAttribute('position',new THREE.BufferAttribute(pos,3));scene.add(new THREE.Points(starGeo,new THREE.PointsMaterial({size:.045,color:0x6defff,transparent:true,opacity:.5})));raycaster=new THREE.Raycaster();pointer=new THREE.Vector2();renderer.domElement.addEventListener('pointermove',e=>{mouseX=e.clientX/innerWidth-.5;mouseY=e.clientY/innerHeight-.5;});renderer.domElement.addEventListener('click',e=>{if(!robot||current>=0)return;pointer.x=e.clientX/innerWidth*2-1;pointer.y=-(e.clientY/innerHeight*2-1);raycaster.setFromCamera(pointer,camera);if(raycaster.intersectObject(robot,true).length)openLesson(0);});addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);});animate();}catch(err){console.error(err);fallback.hidden=false;stage.style.display='none';}}
function material(color,emissive=0){return new THREE.MeshStandardMaterial({color,roughness:.22,metalness:.52,emissive:emissive?color:0x000000,emissiveIntensity:emissive});}
function makeRobot(scale=1){const g=new THREE.Group();const white=material(0xeefaff),dark=new THREE.MeshStandardMaterial({color:0x071426,roughness:.12,metalness:.5}),cyan=material(0x35efff,4),violet=material(0x7657ff,3),pink=material(0xff4fc8,3);const body=new THREE.Mesh(new THREE.SphereGeometry(.72,40,30),white);body.scale.set(1,.9,.76);g.add(body);const chest=new THREE.Mesh(new THREE.TorusGeometry(.16,.035,12,36),cyan);chest.position.set(0,.02,.56);g.add(chest);const core=new THREE.Mesh(new THREE.SphereGeometry(.07,20,16),violet);core.position.set(0,.02,.58);g.add(core);robotParts.core=core;const head=new THREE.Group();head.position.y=1.05;g.add(head);robotParts.head=head;const skull=new THREE.Mesh(new THREE.SphereGeometry(.68,40,30),white);skull.scale.set(1.08,.8,.82);head.add(skull);const visor=new THREE.Mesh(new THREE.BoxGeometry(1.02,.42,.08),dark);visor.position.z=.52;head.add(visor);const eyeL=new THREE.Mesh(new THREE.SphereGeometry(.075,20,16),cyan),eyeR=eyeL.clone();eyeL.position.set(-.22,.02,.59);eyeR.position.set(.22,.02,.59);head.add(eyeL,eyeR);robotParts.eyeL=eyeL;robotParts.eyeR=eyeR;const cheekL=new THREE.Mesh(new THREE.SphereGeometry(.035,16,12),pink),cheekR=cheekL.clone();cheekL.position.set(-.38,-.12,.58);cheekR.position.set(.38,-.12,.58);head.add(cheekL,cheekR);const ant=new THREE.Mesh(new THREE.CylinderGeometry(.022,.022,.34,12),white);ant.position.y=.65;head.add(ant);const tip=new THREE.Mesh(new THREE.SphereGeometry(.07,18,14),pink);tip.position.y=.84;head.add(tip);robotParts.tip=tip;for(const side of [-1,1]){const shoulder=new THREE.Mesh(new THREE.SphereGeometry(.14,22,16),white);shoulder.position.set(side*.76,.08,0);g.add(shoulder);const arm=new THREE.Mesh(new THREE.CylinderGeometry(.09,.1,.56,18),white);arm.position.set(side*.92,-.2,0);arm.rotation.z=side*.32;g.add(arm);const hand=new THREE.Mesh(new THREE.SphereGeometry(.13,20,16),white);hand.position.set(side*1.02,-.5,0);g.add(hand);}const hover=new THREE.Mesh(new THREE.TorusGeometry(.48,.028,10,48),new THREE.MeshBasicMaterial({color:0x35efff,transparent:true,opacity:.55}));hover.rotation.x=Math.PI/2;hover.position.y=-.82;g.add(hover);robotParts.hover=hover;g.scale.setScalar(scale);return g;}
function clearViz(){if(vizGroup)scene.remove(vizGroup);if(robot)scene.remove(robot);vizGroup=new THREE.Group();scene.add(vizGroup);}
function addNode(x,y,z,color=0x35efff,r=.18){const m=new THREE.Mesh(new THREE.SphereGeometry(r,22,16),material(color,2));m.position.set(x,y,z);vizGroup.add(m);return m;}
function addLine(a,b,color=0x6388a8){const geo=new THREE.BufferGeometry().setFromPoints([a.position,b.position]);vizGroup.add(new THREE.Line(geo,new THREE.LineBasicMaterial({color,transparent:true,opacity:.45})));}
function buildHomeScene(){if(!scene)return;clearViz();robot=makeRobot(1.18);robot.position.set(2.05,.05,0);scene.add(robot);for(let i=0;i<4;i++){const r=new THREE.Mesh(new THREE.TorusGeometry(2.15+i*.38,.015,8,96),new THREE.MeshBasicMaterial({color:[0x35efff,0x7657ff,0xff4fc8,0xffb348][i],transparent:true,opacity:.22}));r.position.set(2.05,.45,-.25);r.rotation.x=Math.PI/2+i*.1;vizGroup.add(r);}}
function buildLessonScene(i){if(!scene)return;clearViz();robot=makeRobot(.34);robot.position.set(3.55,-1.35,.7);scene.add(robot);const mode=i%5;if(mode===0){const center=addNode(.3,.2,0,0xffffff,.45);for(let n=0;n<7;n++){const a=n/7*Math.PI*2,o=addNode(Math.cos(a)*2.6,Math.sin(a)*1.45,Math.sin(a*2)*.4,[0x35efff,0x7657ff,0xff4fc8,0xffb348,0xa1ff72][n%5],.26);addLine(o,center);}}else if(mode===1){const layers=[4,6,5,3];layers.forEach((count,li)=>{for(let n=0;n<count;n++)addNode(-3+li*2,(n-(count-1)/2)*.65,Math.sin(n+li)*.25,[0x35efff,0x7657ff,0xff4fc8,0xa1ff72][li],.17);});}else if(mode===2){for(let n=0;n<18;n++){const m=new THREE.Mesh(new THREE.BoxGeometry(.55,.32,.28),material([0x35efff,0x7657ff,0xff4fc8,0xffb348][n%4],1.2));m.position.set((n%6-2.5)*.75,(Math.floor(n/6)-1)*.75,(Math.random()-.5)*.8);m.rotation.y=Math.random()-.5;vizGroup.add(m);}}else if(mode===3){for(let n=0;n<5;n++){const t=new THREE.Mesh(new THREE.TorusGeometry(.55+n*.35,.025,8,72),new THREE.MeshBasicMaterial({color:[0x35efff,0x7657ff,0xff4fc8,0xa1ff72,0xffb348][n],transparent:true,opacity:.5}));t.rotation.set(Math.random()*2,Math.random()*2,0);vizGroup.add(t);}}else{for(let n=0;n<28;n++)addNode((Math.random()-.5)*5,(Math.random()-.5)*3,(Math.random()-.5)*2,[0x35efff,0x7657ff,0xff4fc8,0xa1ff72][n%4],.08+.05*Math.random());}}
const clock=new THREE.Clock();
function animate(){requestAnimationFrame(animate);const t=clock.getElapsedTime();if(robot){const targetY=current<0?.05:-1.35;robot.position.y+=(targetY+Math.sin(t*1.6)*.035-robot.position.y)*.08;if(robotParts.head){robotParts.head.rotation.y+=(mouseX*.35-robotParts.head.rotation.y)*.08;robotParts.head.rotation.x+=(-mouseY*.12-robotParts.head.rotation.x)*.08;}if(robotParts.core)robotParts.core.scale.setScalar(1+Math.sin(t*3)*.14);if(robotParts.tip)robotParts.tip.scale.setScalar(1+Math.sin(t*2.5)*.12);if(robotParts.hover)robotParts.hover.rotation.z=t*.55;const blink=Math.sin(t*.72)>.988?.12:1;if(robotParts.eyeL){robotParts.eyeL.scale.y=blink;robotParts.eyeR.scale.y=blink;}}if(vizGroup)vizGroup.rotation.y+=.0018;renderer?.render(scene,camera);}

renderUI();
init3D();
const slug=location.hash.replace(/^#\/?/,'');
const initial=lessons.findIndex(l=>l.slug===slug);
if(initial>=0)openLesson(initial);else buildHomeScene();
