import * as THREE from 'three';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';

const lessons={
 entertainment:{n:21,slug:'ai-entertainment',title:{en:'AI in Game Development, Animation & Entertainment',fa:'هوش مصنوعی در بازی‌سازی، انیمیشن و صنعت سرگرمی'},text:{
  basic:{en:'AI can accelerate concept development, game assets, animation, NPC behavior, localization, audio, testing, and entertainment production while creators keep artistic control.',fa:'هوش مصنوعی می‌تواند ایده‌پردازی، دارایی‌های بازی، انیمیشن، رفتار NPC، بومی‌سازی، صدا، تست و تولید محتوای سرگرمی را سریع‌تر کند؛ در حالی که کنترل هنری در دست سازندگان باقی می‌ماند.'},
  details:{en:'Think of AI as a production copilot: it can generate first passes and variations, analyze content, assist repetitive work, and help teams iterate faster. Human artists and developers still review, direct, edit, and approve the result.',fa:'AI را می‌توان یک دستیار تولید دانست: نسخه اولیه و تنوع می‌سازد، محتوا را تحلیل می‌کند، کارهای تکراری را سریع‌تر انجام می‌دهد و چرخه تولید را کوتاه می‌کند. هنرمند و توسعه‌دهنده همچنان نتیجه را هدایت، بررسی و نهایی می‌کنند.'},
  advanced:{en:'Real pipelines may combine language, image, video, audio, vision, motion, and behavioral models with game engines and DCC tools. Output must still be checked for consistency, rights, provenance, safety, performance, and production quality.',fa:'در پروژه واقعی ممکن است مدل‌های زبانی، تصویر، ویدئو، صدا، بینایی، حرکت و رفتار با موتور بازی و نرم‌افزارهای تولید محتوا ترکیب شوند. خروجی باید از نظر سازگاری، حقوق محتوا، منبع، ایمنی، کارایی و کیفیت بررسی شود.'}},
  labels:[['Creative Direction','هدایت خلاقه','Ideas, story beats, dialogue variants, mood boards and concept exploration.','ایده، داستان، نسخه‌های دیالوگ، مودبورد و اکتشاف کانسپت.'],['Game Assets','دارایی‌های بازی','Textures, props, environment variants, level drafts and procedural content.','تکسچر، پراپ، تنوع محیط، پیش‌نویس مرحله و محتوای رویه‌ای.'],['Animation','انیمیشن','Pose assistance, motion cleanup, lip sync, facial animation and retargeting.','کمک به پوز، پاک‌سازی حرکت، لب‌خوانی، انیمیشن چهره و Retarget.'],['NPC & Production','NPC و تولید','Context-aware characters, localization, audio workflows, QA, trailers and audience analysis.','کاراکترهای وابسته به زمینه، بومی‌سازی، صدا، کنترل کیفیت، تریلر و تحلیل مخاطب.']]},
 software:{n:22,slug:'ai-software',title:{en:'AI in Programming & Software Projects',fa:'هوش مصنوعی در برنامه‌نویسی و پروژه‌های نرم‌افزاری'},text:{
  basic:{en:'AI coding tools can help plan features, write and explain code, generate tests, debug failures, draft documentation, and automate repetitive engineering tasks.',fa:'ابزارهای AI می‌توانند در برنامه‌ریزی قابلیت‌ها، نوشتن و توضیح کد، ساخت تست، دیباگ، مستندسازی و خودکارسازی کارهای تکراری مهندسی نرم‌افزار کمک کنند.'},
  details:{en:'A strong workflow connects AI to the real repository, documentation, tests, and developer tools, then verifies suggestions by running code, tests, review, and security checks.',fa:'جریان کاری قوی زمانی شکل می‌گیرد که AI به شکل کنترل‌شده به ریپازیتوری واقعی، مستندات، تست‌ها و ابزارهای توسعه وصل شود و پیشنهادها با اجرای کد، تست، Code Review و بررسی امنیتی تأیید شوند.'},
  advanced:{en:'Advanced systems may combine retrieval, tool execution, static analysis, test runners, version control, and agent workflows. Generated code alone does not guarantee correctness, security, scalability, or architectural fit.',fa:'سامانه‌های پیشرفته می‌توانند Retrieval، اجرای ابزار، تحلیل ایستا، Test Runner، کنترل نسخه و Agent Workflow را ترکیب کنند. تولید کد به‌تنهایی صحت، امنیت، مقیاس‌پذیری یا انطباق معماری را تضمین نمی‌کند.'}},
  labels:[['Requirements','نیازمندی‌ها','Turns feature ideas and bug reports into technical tasks and implementation plans.','ایده قابلیت و گزارش باگ را به وظایف فنی و برنامه پیاده‌سازی تبدیل می‌کند.'],['Code Copilot','دستیار کدنویسی','Autocomplete, function drafts, refactoring, explanations and implementation alternatives.','تکمیل کد، ساخت تابع، بازآرایی، توضیح و روش‌های جایگزین پیاده‌سازی.'],['Test & Debug','تست و دیباگ','Generates tests, suggests edge cases, reads errors and narrows likely causes.','تست می‌سازد، حالت مرزی پیشنهاد می‌کند، خطا را می‌خواند و علت‌های محتمل را محدود می‌کند.'],['Architecture & Delivery','معماری و تحویل','Maps dependencies, drafts docs, supports reviews, CI troubleshooting and release work.','وابستگی‌ها را نقشه‌برداری می‌کند و در مستندات، بازبینی، CI و انتشار کمک می‌کند.']]}
};

let active=null,level='basic',renderer,scene,camera,controls,world,raf,clock,targets=[],effects=[],raycaster=new THREE.Raycaster(),pointer=new THREE.Vector2();
let done=new Set();try{const x=JSON.parse(localStorage.getItem('how-ai-practice')||'[]');if(Array.isArray(x))done=new Set(x)}catch{}
const L=()=>document.documentElement.lang==='fa'?'fa':'en';

const css=document.createElement('style');css.textContent=`
.practice3d{position:fixed;inset:0;z-index:2;background:#050b18}.practice3d canvas{display:block;width:100%;height:100%;touch-action:none}.practice-labels{position:fixed;inset:0;z-index:18;pointer-events:none}.panno{position:absolute;display:flex;align-items:center;transform:translate(-4px,-50%);border:0;background:none;color:white;padding:0;pointer-events:auto;cursor:pointer;filter:drop-shadow(0 10px 20px #0008)}.panno.flip{flex-direction:row-reverse;transform:translate(calc(-100% + 4px),-50%)}.panno .dot{width:9px;height:9px;border-radius:50%;background:white;box-shadow:0 0 0 5px #36efff22,0 0 20px #36efff}.panno .wire{width:30px;height:1px;background:#36efff}.panno .pcard{max-width:210px;padding:8px 10px;border:1px solid #9de8ff33;border-radius:10px;background:linear-gradient(135deg,#07182eea,#191234e8);text-align:start;backdrop-filter:blur(12px)}.panno b{display:block;font-size:9px}.panno small{display:none;margin-top:4px;color:#9fc2d1;font-size:8px;line-height:1.35}.panno.active small{display:block}.panno.active .pcard{border-color:#36efff99;box-shadow:0 0 22px #36efff22}@media(max-width:700px){.panno .wire{width:18px}.panno .pcard{max-width:135px;padding:6px 7px}.panno b{font-size:8px}.panno small{font-size:7px}}
`;document.head.appendChild(css);

function progress(){let a=0;try{const p=JSON.parse(localStorage.getItem('how-ai-works-progress')||'[]');if(Array.isArray(p))a=p.length}catch{}return a+done.size}
function syncMeta(){const c=progress(),s=document.querySelector('.journey strong'),b=document.querySelector('.journey em'),m=document.querySelector('.hero-meta span:first-child'),t=`${c}/22`,w=`${c/22*100}%`;if(s&&s.textContent!==t)s.textContent=t;if(b&&b.style.width!==w)b.style.width=w;if(m&&m.textContent!=='22 interactive lessons')m.textContent='22 interactive lessons'}
function injectMenu(){const list=document.querySelector('#lessonList');if(!list||document.querySelector('#practiceLessons'))return;const fa=L()==='fa',g=document.createElement('div');g.id='practiceLessons';g.className='lesson-group';g.innerHTML=`<p>${fa?'هوش مصنوعی در عمل':'AI IN PRACTICE'}</p>${Object.entries(lessons).map(([k,v])=>`<button class="lesson-link" data-practice="${k}"><span>${v.n}</span><b>${v.title[fa?'fa':'en']}</b><i>${done.has(k)?'✓':'→'}</i></button>`).join('')}`;list.appendChild(g);g.querySelectorAll('[data-practice]').forEach(b=>b.onclick=e=>{e.stopPropagation();document.querySelector('#drawer')?.classList.remove('open');openPractice(b.dataset.practice)})}

function renderUI(){if(!active)return;const d=lessons[active],fa=L()==='fa';document.querySelectorAll('.home-ui,.lesson-ui').forEach(x=>{if(x.id!=='practiceUI')x.hidden=true});let u=document.querySelector('#practiceUI');if(!u){u=document.createElement('section');u.id='practiceUI';u.className='lesson-ui';document.querySelector('#ui')?.appendChild(u)}u.hidden=false;u.innerHTML=`<div class="lesson-heading glass"><p class="eyebrow">${d.n} / ${fa?'هوش مصنوعی در عمل':'AI IN PRACTICE'}</p><h1>${d.title[fa?'fa':'en']}</h1><p>${d.text[level][fa?'fa':'en']}</p><div class="level-tabs"><button data-pl="basic" class="${level==='basic'?'active':''}">${fa?'ساده':'Basic'}</button><button data-pl="details" class="${level==='details'?'active':''}">${fa?'جزئیات':'Details'}</button><button data-pl="advanced" class="${level==='advanced'?'active':''}">${fa?'پیشرفته':'Advanced'}</button></div></div><div class="guide-panel glass"><div class="guide-kicker">${fa?'راهنمای سه‌بعدی':'3D GUIDE'}</div><h3 id="pgTitle">${fa?'روی مدل کلیک کنید':'Click a 3D object'}</h3><p id="pgText">${fa?'هر مدل یک کاربرد واقعی AI را نشان می‌دهد.':'Each object represents a real AI-assisted workflow.'}</p></div><nav class="lesson-nav glass"><button id="pp" ${active==='entertainment'?'disabled':''}>← <span>${fa?'قبلی':'Previous'}</span></button><button id="pc" class="complete-btn ${done.has(active)?'done':''}">${done.has(active)?(fa?'تکمیل شده':'Completed'):(fa?'تکمیل درس':'Mark complete')}</button><button id="pn" ${active==='software'?'disabled':''}><span>${fa?'بعدی':'Next'}</span> →</button></nav>`;u.querySelectorAll('[data-pl]').forEach(b=>b.onclick=()=>{level=b.dataset.pl;renderUI()});u.querySelector('#pp').onclick=()=>active==='software'&&openPractice('entertainment');u.querySelector('#pn').onclick=()=>active==='entertainment'&&openPractice('software');u.querySelector('#pc').onclick=()=>{done.has(active)?done.delete(active):done.add(active);localStorage.setItem('how-ai-practice',JSON.stringify([...done]));renderUI();document.querySelector('#practiceLessons')?.remove();injectMenu();syncMeta()};if(targets.length)showTarget(0)}

function mat(c,e=1.3){return new THREE.MeshStandardMaterial({color:c,roughness:.26,metalness:.42,emissive:c,emissiveIntensity:e})}
function node(x,y,c=0x35efff,r=.18,parent=world){const m=new THREE.Mesh(new THREE.SphereGeometry(r,22,16),mat(c,2));m.position.set(x,y,0);parent.add(m);return m}
function box(x,y,c=0x35efff,size=[.9,.55,.36],parent=world){const m=new THREE.Mesh(new THREE.BoxGeometry(...size),mat(c,1.4));m.position.set(x,y,0);parent.add(m);return m}
function arrow(a,b,c=0x35efff){const d=b.clone().sub(a);world.add(new THREE.ArrowHelper(d.clone().normalize(),a,d.length(),c,.16,.08))}
function target(o,data){targets.push({o,data,el:null})}
function controller(){const g=new THREE.Group(),b=new THREE.Mesh(new THREE.BoxGeometry(1.15,.5,.25),mat(0x35efff,1.3));g.add(b);[-1,1].forEach(s=>{const h=new THREE.Mesh(new THREE.SphereGeometry(.27,18,12),mat(0x35efff,1));h.scale.set(.7,1.1,.55);h.position.set(s*.45,-.25,0);g.add(h)});return g}
function rig(){const g=new THREE.Group(),p=[new THREE.Vector3(0,.72,0),new THREE.Vector3(0,.2,0),new THREE.Vector3(0,-.33,0),new THREE.Vector3(-.52,.14,0),new THREE.Vector3(.52,.14,0),new THREE.Vector3(-.28,-1,0),new THREE.Vector3(.28,-1,0)];p.forEach((v,i)=>{const m=new THREE.Mesh(new THREE.SphereGeometry(i?.08:.14,14,9),mat(0xff4fc8,2));m.position.copy(v);g.add(m)});[[0,1],[1,2],[1,3],[1,4],[2,5],[2,6]].forEach(([a,b])=>g.add(new THREE.Line(new THREE.BufferGeometry().setFromPoints([p[a],p[b]]),new THREE.LineBasicMaterial({color:0xc289ff}))));return g}
function codePanel(){const g=new THREE.Group(),s=new THREE.Mesh(new THREE.BoxGeometry(1.55,1.05,.18),new THREE.MeshStandardMaterial({color:0x08172b,metalness:.55,roughness:.2}));g.add(s);g.userData.lines=[];for(let i=0;i<7;i++){const w=.5+(i%4)*.17,l=new THREE.Mesh(new THREE.BoxGeometry(w,.05,.025),new THREE.MeshBasicMaterial({color:[0x35efff,0x7657ff,0xff4fc8,0xa1ff72][i%4]}));l.position.set(-.58+w/2,.35-i*.12,.11);g.add(l);g.userData.lines.push(l)}return g}
function bug(){const g=new THREE.Group(),b=new THREE.Mesh(new THREE.SphereGeometry(.27,18,12),mat(0xff4fc8,2));b.scale.set(1,.7,.6);g.add(b);const r=new THREE.Mesh(new THREE.TorusGeometry(.48,.025,9,40),new THREE.MeshBasicMaterial({color:0x35efff}));r.rotation.x=Math.PI/2;g.add(r);g.userData.r=r;return g}

function entertainment(){const d=lessons.entertainment.labels,core=new THREE.Mesh(new THREE.IcosahedronGeometry(.52,2),mat(0x7657ff,3));world.add(core);const creative=box(-2.7,.9,0x7657ff,[1,.62,.38]),game=controller();game.position.set(-2.4,-.9,0);world.add(game);const anim=rig();anim.position.set(.85,.05,0);anim.scale.setScalar(.9);world.add(anim);const prod=new THREE.Group(),center=node(0,0,0xa1ff72,.28,prod);for(let i=0;i<5;i++){const q=node(Math.cos(i*1.25)*.62,Math.sin(i*1.25)*.62,[0x35efff,0x7657ff,0xff4fc8,0xffb348,0xa1ff72][i],.075,prod);prod.add(new THREE.Line(new THREE.BufferGeometry().setFromPoints([center.position,q.position]),new THREE.LineBasicMaterial({color:0x7de8ff})))}prod.position.set(2.45,.25,0);world.add(prod);[creative,game,anim,prod].forEach((o,i)=>{target(o,d[i]);arrow(core.position.clone(),o.position.clone(),[0x7657ff,0x35efff,0xff4fc8,0xa1ff72][i])});effects.push(t=>{core.rotation.x=t*.25;core.rotation.y=t*.45;creative.position.y=.9+Math.sin(t*1.4)*.07;game.rotation.y=Math.sin(t*.8)*.2;anim.rotation.y=Math.sin(t*.9)*.18;prod.rotation.z=Math.sin(t*.7)*.09})}
function software(){const d=lessons.software.labels,req=box(-2.7,.7,0x35efff,[1,.65,.38]),code=codePanel();code.position.set(-1.05,-.75,0);code.scale.setScalar(.82);world.add(code);const test=bug();test.position.set(.65,.65,0);world.add(test);const arch=new THREE.Group(),c=node(0,0,0xa1ff72,.13,arch);[[-.5,.38,0x7657ff],[.5,.38,0x35efff],[-.5,-.38,0xff4fc8],[.5,-.38,0xffb348]].forEach(([x,y,col])=>{const n=node(x,y,col,.1,arch);arch.add(new THREE.Line(new THREE.BufferGeometry().setFromPoints([c.position,n.position]),new THREE.LineBasicMaterial({color:0xa990ff})))});arch.position.set(2.5,-.35,0);world.add(arch);[req,code,test,arch].forEach((o,i)=>target(o,d[i]));arrow(new THREE.Vector3(-2.15,.48,0),new THREE.Vector3(-1.55,-.4,0));arrow(new THREE.Vector3(-.45,-.5,0),new THREE.Vector3(.25,.35,0),0xff4fc8);arrow(new THREE.Vector3(1.1,.35,0),new THREE.Vector3(2,-.15,0),0xa1ff72);effects.push(t=>{req.rotation.y=Math.sin(t*.8)*.08;code.userData.lines.forEach((l,i)=>l.material.opacity=.45+.5*(.5+.5*Math.sin(t*2-i*.5)));test.userData.r.rotation.z=t*1.2;arch.rotation.z=Math.sin(t*.65)*.06})}

function makeLabels(){const layer=document.createElement('div');layer.id='practiceLabels';layer.className='practice-labels';document.querySelector('.app-shell')?.appendChild(layer);targets.forEach((a,i)=>{const e=document.createElement('button');e.className='panno';e.innerHTML='<span class="dot"></span><span class="wire"></span><span class="pcard"><b></b><small></small></span>';e.onclick=x=>{x.stopPropagation();showTarget(i)};layer.appendChild(e);a.el=e});translateLabels()}
function translateLabels(){const fa=L()==='fa';targets.forEach(a=>{if(!a.el)return;a.el.querySelector('b').textContent=a.data[fa?1:0];a.el.querySelector('small').textContent=a.data[fa?3:2]})}
function showTarget(i){targets.forEach((a,n)=>a.el?.classList.toggle('active',n===i));const d=targets[i]?.data;if(!d)return;const fa=L()==='fa',h=document.querySelector('#pgTitle'),p=document.querySelector('#pgText');if(h)h.textContent=d[fa?1:0];if(p)p.textContent=d[fa?3:2]}

function cleanup(){cancelAnimationFrame(raf);controls?.dispose();renderer?.dispose();document.querySelector('#practiceStage')?.remove();document.querySelector('#practiceLabels')?.remove();renderer=scene=camera=controls=world=null;targets=[];effects=[]}
function build3D(){cleanup();document.querySelector('#annotationLayer')?.setAttribute('hidden','');const host=document.createElement('div');host.id='practiceStage';host.className='practice3d';document.querySelector('.app-shell')?.prepend(host);scene=new THREE.Scene();scene.background=new THREE.Color(0x050b18);scene.fog=new THREE.FogExp2(0x07121f,.035);camera=new THREE.PerspectiveCamera(46,innerWidth/innerHeight,.1,100);camera.position.set(0,.5,8.5);renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.setSize(innerWidth,innerHeight);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.1;host.appendChild(renderer.domElement);controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.enablePan=false;controls.minDistance=5.5;controls.maxDistance=11;scene.add(new THREE.HemisphereLight(0xc5f7ff,0x130826,2.2));const k=new THREE.DirectionalLight(0xffffff,2.8);k.position.set(4,7,5);scene.add(k);const p=new THREE.PointLight(0x35efff,20,18);p.position.set(-4,2,4);scene.add(p);const q=new THREE.PointLight(0xff4fc8,14,15);q.position.set(4,1,2);scene.add(q);const grid=new THREE.GridHelper(34,34,0x2a7ea0,0x143249);grid.position.y=-2;grid.material.transparent=true;grid.material.opacity=.14;scene.add(grid);world=new THREE.Group();scene.add(world);active==='entertainment'?entertainment():software();makeLabels();renderer.domElement.addEventListener('click',click3D);resize();clock=new THREE.Clock();animate()}
function click3D(e){const r=renderer.domElement.getBoundingClientRect();pointer.set((e.clientX-r.left)/r.width*2-1,-((e.clientY-r.top)/r.height*2-1));raycaster.setFromCamera(pointer,camera);const hit=raycaster.intersectObjects(targets.map(x=>x.o),true)[0];if(!hit)return;let o=hit.object,i=-1;while(o&&i<0){i=targets.findIndex(x=>x.o===o);o=o.parent}if(i>=0)showTarget(i)}
const tv=new THREE.Vector3();function positionLabels(){if(!renderer)return;const r=renderer.domElement.getBoundingClientRect();targets.forEach(a=>{a.o.getWorldPosition(tv);const v=tv.clone().project(camera),x=(v.x*.5+.5)*r.width,y=(-v.y*.5+.5)*r.height;a.el.style.display=v.z>-1&&v.z<1?'flex':'none';a.el.style.left=`${Math.max(16,Math.min(innerWidth-16,x))}px`;a.el.style.top=`${Math.max(76,Math.min(innerHeight-65,y))}px`;a.el.classList.toggle('flip',x>innerWidth*.68)})}
function resize(){if(!renderer)return;camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);const m=innerWidth<720;world.scale.setScalar(m?.73:1);world.position.y=m?-.42:0}
function animate(){raf=requestAnimationFrame(animate);const t=clock.getElapsedTime();controls.update();world.rotation.y+=.001;effects.forEach(f=>f(t));positionLabels();renderer.render(scene,camera)}

function openPractice(k){active=k;level='basic';location.hash=`#/${lessons[k].slug}`;renderUI();build3D();syncMeta()}
function closePractice(){if(!active)return;active=null;cleanup();document.querySelector('#practiceUI')?.remove();document.querySelector('#annotationLayer')?.removeAttribute('hidden')}
function sync(){syncMeta();injectMenu();if(active&&!document.querySelector('#practiceUI')){renderUI();translateLabels()}}
new MutationObserver(()=>queueMicrotask(sync)).observe(document.querySelector('#ui'),{childList:true,subtree:true});
addEventListener('resize',resize);document.addEventListener('click',e=>{if(e.target.closest('#homeBtn')||e.target.closest('.lesson-link:not([data-practice])'))closePractice()},true);
const h=location.hash.replace(/^#\/?/,'');const start=Object.entries(lessons).find(([,v])=>v.slug===h)?.[0];setTimeout(()=>{sync();if(start)openPractice(start)},0);
